fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        name: "[file -  check] large file"
        args: [--maxkb=5000]
      - id: check-ast
        name: "[py   -  check] validate python"
      - id: check-builtin-literals
        name: "[py   -  check] builtin literals"
      - id: check-byte-order-marker
        name: "[file -  check] byte order marker"
      - id: check-case-conflict
        name: "[file -  check] case conflict"
      - id: check-docstring-first
        name: "[py   -  check] docstring first"
      - id: check-json
        name: "[json -  check] validate json"
      - id: check-merge-conflict
        name: "[git  -  check] merge conflict"
      - id: check-symlinks
        name: "[link -  check] broken symlinks"
      - id: check-yaml
        name: "[yaml -  check] validate yaml"
      - id: check-xml
        name: "[xml  -  check] validate xml"
      - id: debug-statements
        name: "[py   -  check] debug statements"
      - id: detect-private-key
        name: "[cred -  check] private keys"
      - id: end-of-file-fixer
        name: "[file - format] end of files"
      - id: fix-encoding-pragma
        name: "[file - format] coding pragma"
        args: [--remove]
      - id: mixed-line-ending
        name: "[file - format] mixed line ending"
        args: [--fix=auto]
      - id: trailing-whitespace
        name: "[file - format] trim trailing whitespace"
        args: [--markdown-linebreak-ext=md]

  - repo: https://github.com/PyCQA/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args: [--profile=black]
        name: "[py   - format] isort"

  - repo: https://github.com/PyCQA/docformatter
    rev: v1.7.7
    hooks:
      - id: docformatter
        args: [--wrap-summaries=88, --wrap-descriptions=88, -i]
        name: "[py   - format] docformatter"

  - repo: https://github.com/ambv/black
    rev: 25.1.0
    hooks:
      - id: black
        name: "[py   - format] black"

  - repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        name: "[py   -  check] flake8"

  - repo: https://github.com/lovesegfault/beautysh
    rev: v6.2.1
    hooks:
      - id: beautysh
        name: "[bash - format] beautysh"

  - repo: https://github.com/detailyang/pre-commit-shell
    rev: 1.0.5
    hooks:
      - id: shell-lint
        name: "[bash -   lint] shell-lint"
